In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
chronic_kidney_disease = fetch_ucirepo(id=336) 
  
# data (as pandas dataframes) 
x = chronic_kidney_disease.data.features 
y = chronic_kidney_disease.data.targets 

x

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,hemo,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,15.4,44.0,7800.0,5.2,yes,yes,no,good,no,no
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,11.3,38.0,6000.0,NaN,no,no,no,good,no,no
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,9.6,31.0,7500.0,NaN,no,yes,no,poor,no,yes
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,11.2,32.0,6700.0,3.9,yes,no,no,poor,yes,yes
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,11.6,35.0,7300.0,4.6,no,no,no,good,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,...,15.7,47.0,6700.0,4.9,no,no,no,good,no,no
396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,16.5,54.0,7800.0,6.2,no,no,no,good,no,no
397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,15.8,49.0,6600.0,5.4,no,no,no,good,no,no
398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,...,14.2,51.0,7200.0,5.9,no,no,no,good,no,no
399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,...,15.8,53.0,6800.0,6.1,no,no,no,good,no,no

In [3]:
y

      class
0       ckd
1       ckd
2       ckd
3       ckd
4       ckd
..      ...
395  notckd
396  notckd
397  notckd
398  notckd
399  notckd

[400 rows x 1 columns]

In [4]:
chronic_kidney_disease.targets

In [5]:
df = x.drop(columns=['rbc', 'pc', 'pcc', 'ba', 'sc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane'])
df

,age,bp,sg,al,su,bgr,bu,sod,pot,hemo,pcv,wbcc,rbcc
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,NaN,NaN,15.4,44.0,7800.0,5.2
1,7.0,50.0,1.020,4.0,0.0,NaN,18.0,NaN,NaN,11.3,38.0,6000.0,NaN
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,NaN,NaN,9.6,31.0,7500.0,NaN
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,111.0,2.5,11.2,32.0,6700.0,3.9
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,NaN,NaN,11.6,35.0,7300.0,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,140.0,49.0,150.0,4.9,15.7,47.0,6700.0,4.9
396,42.0,70.0,1.025,0.0,0.0,75.0,31.0,141.0,3.5,16.5,54.0,7800.0,6.2
397,12.0,80.0,1.020,0.0,0.0,100.0,26.0,137.0,4.4,15.8,49.0,6600.0,5.4
398,17.0,60.0,1.025,0.0,0.0,114.0,50.0,135.0,4.9,14.2,51.0,7200.0,5.9
399,58.0,80.0,1.025,0.0,0.0,131.0,18.0,141.0,3.5,15.8,53.0,6800.0,6.1

In [6]:
print(chronic_kidney_disease.variables)

     name     role         type demographic              description  \
0     age  Feature      Integer         Age                      NaN
1      bp  Feature      Integer         NaN           blood pressure
2      sg  Feature  Categorical         NaN         specific gravity
3      al  Feature  Categorical         NaN                  albumin
4      su  Feature  Categorical         NaN                    sugar
5     rbc  Feature       Binary         NaN          red blood cells
6      pc  Feature       Binary         NaN                 pus cell
7     pcc  Feature       Binary         NaN          pus cell clumps
8      ba  Feature       Binary         NaN                 bacteria
9     bgr  Feature      Integer         NaN     blood glucose random
10     bu  Feature      Integer         NaN               blood urea
11     sc  Feature   Continuous         NaN         serum creatinine
12    sod  Feature      Integer         NaN                   sodium
13    pot  Feature   Continuous         NaN                potassium
14   hemo  Feature   Continuous         NaN               hemoglobin
15    pcv  Feature      Integer         NaN       packed cell volume
16   wbcc  Feature      Integer         NaN   white blood cell count
17   rbcc  Feature   Continuous         NaN     red blood cell count
18    htn  Feature       Binary         NaN             hypertension
19     dm  Feature       Binary         NaN        diabetes mellitus
20    cad  Feature       Binary         NaN  coronary artery disease
21  appet  Feature       Binary         NaN                 appetite
22     pe  Feature       Binary         NaN              pedal edema
23    ane  Feature       Binary         NaN                   anemia
24  class   Target       Binary         NaN           ckd or not ckd

           units missing_values
0           year            yes
1          mm/Hg            yes
2            NaN            yes
3            NaN            yes
4            NaN            yes
5            NaN            yes
6            NaN            yes
7            NaN            yes
8            NaN            yes
9         mgs/dl            yes
10        mgs/dl            yes
11        mgs/dl            yes
12         mEq/L            yes
13         mEq/L            yes
14           gms            yes
15           NaN            yes
16     cells/cmm            yes
17  millions/cmm            yes
18           NaN            yes
19           NaN            yes
20           NaN            yes
21           NaN            yes
22           NaN            yes
23           NaN            yes
24           NaN             no

In [7]:
chronic_kidney_disease.data.targets

      class
0       ckd
1       ckd
2       ckd
3       ckd
4       ckd
..      ...
395  notckd
396  notckd
397  notckd
398  notckd
399  notckd

[400 rows x 1 columns]

In [8]:
df['hemo'] = df['hemo'] * 10
df

,age,bp,sg,al,su,bgr,bu,sod,pot,hemo,pcv,wbcc,rbcc
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,NaN,NaN,154.0,44.0,7800.0,5.2
1,7.0,50.0,1.020,4.0,0.0,NaN,18.0,NaN,NaN,113.0,38.0,6000.0,NaN
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,NaN,NaN,96.0,31.0,7500.0,NaN
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,111.0,2.5,112.0,32.0,6700.0,3.9
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,NaN,NaN,116.0,35.0,7300.0,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,140.0,49.0,150.0,4.9,157.0,47.0,6700.0,4.9
396,42.0,70.0,1.025,0.0,0.0,75.0,31.0,141.0,3.5,165.0,54.0,7800.0,6.2
397,12.0,80.0,1.020,0.0,0.0,100.0,26.0,137.0,4.4,158.0,49.0,6600.0,5.4
398,17.0,60.0,1.025,0.0,0.0,114.0,50.0,135.0,4.9,142.0,51.0,7200.0,5.9
399,58.0,80.0,1.025,0.0,0.0,131.0,18.0,141.0,3.5,158.0,53.0,6800.0,6.1

In [9]:
y.dtypes

class    str
dtype: object

In [10]:
y['class'].unique()

<ArrowStringArray>
['ckd', 'ckd\t', 'notckd']
Length: 3, dtype: str

In [11]:
y['class'] = y['class'].replace({'ckd\t': 'ckd'})

In [12]:
y['class'].unique()

<ArrowStringArray>
['ckd', 'notckd']
Length: 2, dtype: str

In [13]:
y['class'] = y['class'].replace({'ckd': 'a', 'notckd': 'c'})

In [14]:
y['class'].unique()

<ArrowStringArray>
['a', 'c']
Length: 2, dtype: str

In [15]:
y

    class
0       a
1       a
2       a
3       a
4       a
..    ...
395     c
396     c
397     c
398     c
399     c

[400 rows x 1 columns]

In [16]:
df = df.join(y)

In [17]:
df

,age,bp,sg,al,su,bgr,bu,sod,pot,hemo,pcv,wbcc,rbcc,class
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,NaN,NaN,154.0,44.0,7800.0,5.2,a
1,7.0,50.0,1.020,4.0,0.0,NaN,18.0,NaN,NaN,113.0,38.0,6000.0,NaN,a
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,NaN,NaN,96.0,31.0,7500.0,NaN,a
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,111.0,2.5,112.0,32.0,6700.0,3.9,a
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,NaN,NaN,116.0,35.0,7300.0,4.6,a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,140.0,49.0,150.0,4.9,157.0,47.0,6700.0,4.9,c
396,42.0,70.0,1.025,0.0,0.0,75.0,31.0,141.0,3.5,165.0,54.0,7800.0,6.2,c
397,12.0,80.0,1.020,0.0,0.0,100.0,26.0,137.0,4.4,158.0,49.0,6600.0,5.4,c
398,17.0,60.0,1.025,0.0,0.0,114.0,50.0,135.0,4.9,142.0,51.0,7200.0,5.9,c
399,58.0,80.0,1.025,0.0,0.0,131.0,18.0,141.0,3.5,158.0,53.0,6800.0,6.1,c

In [18]:
df.describe

<bound method NDFrame.describe of       age    bp     sg   al   su    bgr    bu    sod  pot   hemo   pcv  \
0    48.0  80.0  1.020  1.0  0.0  121.0  36.0    NaN  NaN  154.0  44.0
1     7.0  50.0  1.020  4.0  0.0    NaN  18.0    NaN  NaN  113.0  38.0
2    62.0  80.0  1.010  2.0  3.0  423.0  53.0    NaN  NaN   96.0  31.0
3    48.0  70.0  1.005  4.0  0.0  117.0  56.0  111.0  2.5  112.0  32.0
4    51.0  80.0  1.010  2.0  0.0  106.0  26.0    NaN  NaN  116.0  35.0
..    ...   ...    ...  ...  ...    ...   ...    ...  ...    ...   ...
395  55.0  80.0  1.020  0.0  0.0  140.0  49.0  150.0  4.9  157.0  47.0
396  42.0  70.0  1.025  0.0  0.0   75.0  31.0  141.0  3.5  165.0  54.0
397  12.0  80.0  1.020  0.0  0.0  100.0  26.0  137.0  4.4  158.0  49.0
398  17.0  60.0  1.025  0.0  0.0  114.0  50.0  135.0  4.9  142.0  51.0
399  58.0  80.0  1.025  0.0  0.0  131.0  18.0  141.0  3.5  158.0  53.0

       wbcc  rbcc class
0    7800.0   5.2     a
1    6000.0   NaN     a
2    7500.0   NaN     a
3    6700.0   3.9     a
4    7300.0   4.6     a
..      ...   ...   ...
395  6700.0   4.9     c
396  7800.0   6.2     c
397  6600.0   5.4     c
398  7200.0   5.9     c
399  6800.0   6.1     c

[400 rows x 14 columns]>

In [19]:
df.head(20)

,age,bp,sg,al,su,bgr,bu,sod,pot,hemo,pcv,wbcc,rbcc,class
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,NaN,NaN,154.0,44.0,7800.0,5.2,a
1,7.0,50.0,1.020,4.0,0.0,NaN,18.0,NaN,NaN,113.0,38.0,6000.0,NaN,a
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,NaN,NaN,96.0,31.0,7500.0,NaN,a
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,111.0,2.5,112.0,32.0,6700.0,3.9,a
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,NaN,NaN,116.0,35.0,7300.0,4.6,a
5,60.0,90.0,1.015,3.0,0.0,74.0,25.0,142.0,3.2,122.0,39.0,7800.0,4.4,a
6,68.0,70.0,1.010,0.0,0.0,100.0,54.0,104.0,4.0,124.0,36.0,NaN,NaN,a
7,24.0,NaN,1.015,2.0,4.0,410.0,31.0,NaN,NaN,124.0,44.0,6900.0,5.0,a
8,52.0,100.0,1.015,3.0,0.0,138.0,60.0,NaN,NaN,108.0,33.0,9600.0,4.0,a
9,53.0,90.0,1.020,2.0,0.0,70.0,107.0,114.0,3.7,95.0,29.0,12100.0,3.7,a
10,50.0,60.0,1.010,2.0,4.0,490.0,55.0,NaN,NaN,94.0,28.0,NaN,NaN,a
11,63.0,70.0,1.010,3.0,0.0,380.0,60.0,131.0,4.2,108.0,32.0,4500.0,3.8,a
12,68.0,70.0,1.015,3.0,1.0,208.0,72.0,138.0,5.8,97.0,28.0,12200.0,3.4,a
13,68.0,70.0,NaN,NaN,NaN,98.0,86.0,135.0,3.4,98.0,NaN,NaN,NaN,a
14,68.0,80.0,1.010,3.0,2.0,157.0,90.0,130.0,6.4,56.0,16.0,11000.0,2.6,a
15,40.0,80.0,1.015,3.0,0.0,76.0,162.0,141.0,4.9,76.0,24.0,3800.0,2.8,a
16,47.0,70.0,1.015,2.0,0.0,99.0,46.0,138.0,4.1,126.0,NaN,NaN,NaN,a
17,47.0,80.0,NaN,NaN,NaN,114.0,87.0,139.0,3.7,121.0,NaN,NaN,NaN,a
18,60.0,100.0,1.025,0.0,3.0,263.0,27.0,135.0,4.3,127.0,37.0,11400.0,4.3,a
19,62.0,60.0,1.015,1.0,0.0,100.0,31.0,NaN,NaN,103.0,30.0,5300.0,3.7,a

In [20]:
#z = df.isnull().values.sum(axis=1)
#z

df = df[df.isnull().values.sum(axis=1) < 3]
df

,age,bp,sg,al,su,bgr,bu,sod,pot,hemo,pcv,wbcc,rbcc,class
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,NaN,NaN,154.0,44.0,7800.0,5.2,a
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,111.0,2.5,112.0,32.0,6700.0,3.9,a
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,NaN,NaN,116.0,35.0,7300.0,4.6,a
5,60.0,90.0,1.015,3.0,0.0,74.0,25.0,142.0,3.2,122.0,39.0,7800.0,4.4,a
6,68.0,70.0,1.010,0.0,0.0,100.0,54.0,104.0,4.0,124.0,36.0,NaN,NaN,a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,140.0,49.0,150.0,4.9,157.0,47.0,6700.0,4.9,c
396,42.0,70.0,1.025,0.0,0.0,75.0,31.0,141.0,3.5,165.0,54.0,7800.0,6.2,c
397,12.0,80.0,1.020,0.0,0.0,100.0,26.0,137.0,4.4,158.0,49.0,6600.0,5.4,c
398,17.0,60.0,1.025,0.0,0.0,114.0,50.0,135.0,4.9,142.0,51.0,7200.0,5.9,c
399,58.0,80.0,1.025,0.0,0.0,131.0,18.0,141.0,3.5,158.0,53.0,6800.0,6.1,c

In [22]:
#df.dropna(axis=0, thresh=10, inplace=True)
#df

In [23]:
df.head(20)

,age,bp,sg,al,su,bgr,bu,sod,pot,hemo,pcv,wbcc,rbcc,class
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,NaN,NaN,154.0,44.0,7800.0,5.2,a
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,111.0,2.5,112.0,32.0,6700.0,3.9,a
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,NaN,NaN,116.0,35.0,7300.0,4.6,a
5,60.0,90.0,1.015,3.0,0.0,74.0,25.0,142.0,3.2,122.0,39.0,7800.0,4.4,a
6,68.0,70.0,1.010,0.0,0.0,100.0,54.0,104.0,4.0,124.0,36.0,NaN,NaN,a
8,52.0,100.0,1.015,3.0,0.0,138.0,60.0,NaN,NaN,108.0,33.0,9600.0,4.0,a
9,53.0,90.0,1.020,2.0,0.0,70.0,107.0,114.0,3.7,95.0,29.0,12100.0,3.7,a
11,63.0,70.0,1.010,3.0,0.0,380.0,60.0,131.0,4.2,108.0,32.0,4500.0,3.8,a
12,68.0,70.0,1.015,3.0,1.0,208.0,72.0,138.0,5.8,97.0,28.0,12200.0,3.4,a
14,68.0,80.0,1.010,3.0,2.0,157.0,90.0,130.0,6.4,56.0,16.0,11000.0,2.6,a
15,40.0,80.0,1.015,3.0,0.0,76.0,162.0,141.0,4.9,76.0,24.0,3800.0,2.8,a
18,60.0,100.0,1.025,0.0,3.0,263.0,27.0,135.0,4.3,127.0,37.0,11400.0,4.3,a
19,62.0,60.0,1.015,1.0,0.0,100.0,31.0,NaN,NaN,103.0,30.0,5300.0,3.7,a
20,61.0,80.0,1.015,2.0,0.0,173.0,148.0,135.0,5.2,77.0,24.0,9200.0,3.2,a
22,48.0,80.0,1.025,4.0,0.0,95.0,163.0,136.0,3.8,98.0,32.0,6900.0,3.4,a
24,42.0,100.0,1.015,4.0,0.0,NaN,50.0,129.0,4.0,111.0,39.0,8300.0,4.6,a
25,61.0,60.0,1.025,0.0,0.0,108.0,75.0,141.0,5.2,99.0,29.0,8400.0,3.7,a
26,75.0,80.0,1.015,0.0,0.0,156.0,45.0,140.0,3.4,116.0,35.0,10300.0,4.0,a
27,69.0,70.0,1.010,3.0,4.0,264.0,87.0,130.0,4.0,125.0,37.0,9600.0,4.1,a
31,73.0,90.0,1.015,3.0,0.0,107.0,33.0,141.0,4.6,101.0,30.0,7800.0,4.0,a